### ISSUE TITLE
Add-in doesn't fetch Drive information

### ISSUE THREAD

**Issue by sumurthy** [OfficeDev/Office-Add-in-NodeJS-SSO#2]
Once I got this to load in PowerPoint, the Add-in doesn't do anything. the "Get my files from OneDrive" just grays out and nothing happens. 

![image](https://user-images.githubusercontent.com/8384457/27015804-865c6acc-4ecc-11e7-9a22-4d94a39b7e3f.png)

**Comment by Rick-Kirkham** [comment]
I can reproduce this. Office is returning error 13007 "Error occurred in the authentication provider." This means that Office is not getting a token from the AAD V2 endpoint. This is a problem that can't be fixed in the sample itself. I reported it yesterday. I'll loop you on the email thread.

**Comment by ensemble-joe** [comment]
Would you be able to provide an update to this issue?  Or possible resolution?  I have tried this sample add-in a few days ago, and I'm getting the same error (13007).

**Comment by Rick-Kirkham** [comment]
@ensemble-joe 
Other people fixed 13007 by going to the add-in registration and asking for "profile" permission to Microsoft Graph in addition to "files-read-all". You then have to redo the admin consent procedure too. 

I've held off updating the documentation because there are several other changes coming soon.

**Comment by ensemble-joe** [comment]
@Rick-Kirkham 
Thanks for your reply.
I have added "profile" permission and redo the admin consent, but I'm still getting the same error (13007)
<img width="761" alt="screen shot 2017-09-15 at 12 21 51 pm" src="https://user-images.githubusercontent.com/19603833/30501054-c25b9784-9a15-11e7-9c75-6bf309dfacc5.png">

Any other workaround I can try?  Also, do you have an ETA on when the documentation will be updated to reflect the latest behavior?

**Comment by PieterVm** [comment]
Same issue here..

**Comment by Rick-Kirkham** [comment]
@PieterVm Are you working with this NodeJS sample or with the ASP.NET sample? You've created an issue on the ASP.NET sample repo and added to this one. I'm asking because the registration permissions needed are different for the two samples. The ASP.NEt sample uses MSAL which internally requires 2 additional permissions that this NodeJS sample does not require.

**Comment by PieterVm** [comment]
I'm working with the ASP version and followed that tutorial.

**Comment by Rick-Kirkham** [comment]
In that case, I'll close this. Please raise the issue for the ASP.NET sample. It is confusing for others to track it here in the NodeJS sample.
